// scripts/build-icons.mjs
// Generates src/ui/icons.generated.ts — an SVG <symbol> sprite built from
// lucide-static (ISC, no attribution required).
//
// Why a sprite and not inline SVG: inline is the right call up to roughly
// 15-20 icons on a page; past that the duplication costs more than the sprite
// indirection. This UI is well past that line.
//
// The generated file is committed, so a normal build and the dev server never
// depend on this script running. Re-run it (npm run build-icons) after editing
// ICONS below.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const OUT = path.join(__dirname, '..', 'src', 'ui', 'icons.generated.ts');

// Semantic name -> lucide icon. Panels reference the left column, so swapping
// the glyph for a concept is a one-line change here.
const ICONS = {
  // toolbar
  build: 'hammer',
  finance: 'coins',
  guests: 'users',
  staff: 'wrench',
  objectives: 'target',
  sound: 'volume-2',
  save: 'save',
  account: 'circle-user',
  leaderboard: 'trophy',
  // toolbar readouts
  cash: 'banknote',
  clock: 'clock',
  mood: 'smile',
  rating: 'star',
  // speed controls
  pause: 'pause',
  play: 'play',
  fastForward: 'fast-forward',
  // window chrome
  close: 'x',
  minimize: 'minus',
  restore: 'square',
  // actions
  bulldoze: 'trash-2',
  freePlay: 'dice-5',
  stepUp: 'plus',
  stepDown: 'minus',
  // guest mood
  moodHappy: 'smile',
  moodNeutral: 'meh',
  moodSad: 'frown',
  // guest archetypes
  highRoller: 'gem',
  biker: 'bike',
  tourist: 'camera',
  thought: 'message-circle',
  // staff roles
  mechanic: 'wrench',
  janitor: 'brush',
  bartender: 'martini',
  waitress: 'wine',
  pitBoss: 'user-round-cog',
  security: 'shield',
  dealer: 'spade',
  cashier: 'hand-coins',
  // build catalog (src/data/objects.ts references these by name)
  'slot-machine': 'cherry',
  'blackjack-table': 'spade',
  'craps-table': 'dice-5',
  'roulette-table': 'circle-dot',
  'big-six-wheel': 'disc-3',
  'poker-table': 'club',
  'high-limit-table': 'gem',
  // P17 Part B Tier 1
  'penny-slots': 'coins',
  pachinko: 'circle-dot-dashed',
  'keno-lounge': 'grid-3x3',
  'video-poker': 'monitor',
  toilet: 'toilet',
  'food-stall': 'sandwich',
  plant: 'sprout',
  'neon-sign': 'signpost',
  marquee: 'sparkles',
  bar: 'martini',
  cage: 'vault',
  // status / flavor
  music: 'music',
  effects: 'bell',
  mute: 'volume-x',
  celebrate: 'party-popper',
  fail: 'trending-down',
  // Track 2 — daily conditions, reputation, comps
  modifier: 'cloud-lightning',
  reputation: 'megaphone',
  comp: 'gift',
  overlay: 'layers',
  // Track 4 — carded patrons
  patrons: 'id-card',
  patronTier: 'crown',
};

/** Strips the wrapper <svg> down to its drawing content. Presentation
 *  attributes are dropped on purpose — they live on the .icon CSS class, so a
 *  single rule restyles the whole set. */
async function symbolFor(name, file) {
  const raw = await readFile(path.join(SRC, `${file}.svg`), 'utf8');
  const inner = raw
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .join('');
  if (!inner) throw new Error(`No drawing content extracted from ${file}.svg`);
  return `<symbol id="i-${name}" viewBox="0 0 24 24">${inner}</symbol>`;
}

const symbols = [];
for (const [name, file] of Object.entries(ICONS)) {
  symbols.push(await symbolFor(name, file));
}

const names = Object.keys(ICONS)
  .map((n) => `  | '${n}'`)
  .join('\n');

const out = `// GENERATED by scripts/build-icons.mjs — do not edit.
// Icons from lucide-static (ISC). Re-run: npm run build-icons

export type IconName =
${names};

export const ICON_SPRITE =
  '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="display:none">' +
${symbols.map((s) => `  ${JSON.stringify(s)}`).join(' +\n')} +
  '</svg>';
`;

await writeFile(OUT, out);
console.log(`Wrote ${Object.keys(ICONS).length} icons to ${path.relative(process.cwd(), OUT)}`);
